package com.example.finance.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.Data;

/*
 * author: Prasanna
 * 
 * Category represents a category entity associated with a user.
 * It contains information about the category's name, description, and its association with a user.
 */
@Data
@Entity
public class Category {
    // Unique identifier for the category, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // Name of the category
    private String name;
    
    // Description of the category
    private String description;

    /*
     * Many-to-one relationship with AuthUser.
     * A category belongs to one user.
     * 
     * The @JsonBackReference annotation ensures that the user's reference to the category is not serialized 
     * to avoid infinite recursion during JSON serialization.
     */
    @ManyToOne // Fetch type LAZY loads the related entity only when needed
    @JoinColumn(name = "user_id")
    // Prevents circular serialization issues
    private AuthUser user;

    // getters and setters
}
